### ISSUE TITLE
Need to click on pathway to enable zoom with scroll button

### ISSUE THREAD

**Issue by thomaskelder** [wikipathways/pvjs#146]
Zooming with the scroll button didn't work for me until after I clicked on the pathway. Expected behavior is that it works as soon as you hover over the pathway and scroll with the mouse.

Issue observed in Chrome Version 31.0.1650.63

**Comment by khanspers** [comment]
Since neither vehement disagreement or alternative UX ideas have surfaced, I am closing this.
