### ISSUE TITLE
Focus view on search result

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#151]
Should the viewer focus the view (by pan/zoom) on nodes found through search? Right now, if the pathway has been zoomed in or panned so that the found node is not in the view, the user can't see the search result. 

Factors to consider: The user may have carefully adjusted the view and refocusing automatically may be disruptive. Maybe only refocus if the node is completely out of the view.

**Comment by khanspers** [comment]
After doing a lot of searching for nodes on pathways (after zooming/panning) in the past week, I think we should bump the priority on this one. I think it's safe to assume that of the user starts a data node search while zoomed in its because they want to find one or more specific node(s). So it's pretty annoying to have to zoom out / pan manually after the search is done, it even might seem buggy to users. Of course the best case is an intelligent pan (and possible zoom) to refocus the view minimally from the user selected view, but even the easy solution of zoom-to-fit pathway would be better than the current situation.

**Comment by ariutta** [comment]
+1. It's frustrating for me when I try to find a node in a pathway, and then the highlighted node isn't visible. How about this order of priority:

1) Quick editor online (currently held up by pvjs.wikipathways.org server being down)
2) Diff viewer
3) This

**Comment by khanspers** [comment]
Sounds reasonable, but we should review if there are other features that have higher priority than this, after the editor and diff viewer.

**Comment by ariutta** [comment]
Good point. Where would you place Issue #307 on the list?

@AlexanderPico might have some input here too on prioritization.
