### ISSUE TITLE
MBostock's tip on updating across groups of g elements

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#184]
Sometimes you have to make nesting decisions that are counter to *some* of your selection use cases; or you might just be working with a flat model.  Using this syntax, you can define groups programmatically, independent of your model:

```
  <svg:g class="circle">
    <svg:image/>
    <svg:image/>
    …
  </svg:g>
  <svg:g class="nodetext">
    <svg:text/>
    <svg:text/>
    …
  </svg:g>
```

This will require changing how you update the nodes. Though, you can merge the two
selections together for update:
```
  node = vis.selectAll("g.circle image, g.nodetext text");
```
From second post in this thread: https://groups.google.com/forum/#!topic/d3-js/JCXKef_GRCQ

**Comment by khanspers** [comment]
@ariutta: Assuming this cane be closed?

**Comment by ariutta** [comment]
Yes, you're right.
