### ISSUE TITLE
Zoom/Pan issues on Windows 8/IE10

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#190]
1. Zoom doesn't work at all, either by mouse scroll or double-click
2. Pan sort of works, but the pathway doesn't stay inside the viewer bounds. See attached.

![panzoom_ie10](https://f.cloud.github.com/assets/1442197/2023206/de97120c-8858-11e3-8434-31cd9cc54773.png)

**Comment by khanspers** [comment]
Why is this tagged as diffviewer? Seems to be viewer related.

**Comment by ariutta** [comment]
I think it showed up specifically for the diff-viewer. Not sure whether it
was for the viewer in general.

**Comment by CapRoberts** [comment]
Just build a website using this library and now seen that it does not work at all on IE11.
The online demos do not work either, guess I will have to change my design and try something else.

**Comment by ariutta** [comment]
It's worked on IE11 for me. Can you further describe the issue, possibly
with screenshots?
