### ISSUE TITLE
Drag to Move Icon for Annotations Panel

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#224]
@samadlotia had a good suggestion for the drag behavior of the Annotations Panel. Right now, we have a four-headed arrow as the "Move" icon. We could instead make it work like most application windows work where dragging the top section of the window moves the window.

**Comment by AlexanderPico** [comment]
I think we had that at one point, until we added the close button to the top of the window... maybe the draggable area could be extended to the right up to the close button?  But we should keep the 4-point icon regardless.

**Comment by khanspers** [comment]
Making the whole top section usable for dragging is intuitive. Although we should indicate this somehow, maybe with a slightly darker grey top (across the panel). And the 4-point icon should be removed then.

**Comment by ariutta** [comment]
Relevant discussion on how to indicate "draggability":
http://ux.stackexchange.com/questions/45443/the-hamburger-icon-menu-or-drag-affordance

**Comment by khanspers** [comment]
If we want to keep an icon to indicate draggability, we should stick with the one we already have (definitely not the hamburger icon.....). But I think indicating the entire top of the panel with a darker grey strip across the top is more effective.

**Comment by ariutta** [comment]
Sounds good to me.
