### ISSUE TITLE
Clicking on Pathway DataNodes do not open data panel

### ISSUE THREAD

**Issue by egonw** [wikipathways/pvjs#252]
E.g. http://www.wikipathways.org/index.php/Pathway:WP2622

The "Calvin-Benson Cycle" DataNode links to another pathway (with WP ID), but does not open a popup dialog.

**Comment by khanspers** [comment]
Data panel only appears for pathway data nodes that are rectangles (as defined by user, not default) but not for default pathway nodes, even if pathway identifier is assigned. See:

http://wikipathways.org/index.php/Pathway:WP2447: synaptic transmission, glutamatergic
vs
http://wikipathways.org/index.php/Pathway:WP534: Pentose Phosphate Pathway
