### ISSUE TITLE
Initial zoom for empty pathway

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#281]
If you view a pathway that only has the titleblock in the upper left, the zoom is too far in. Can we set a maximum zoom for pathways like this?

http://localhost:3000/test/one-diagram.html?gpml=http://localhost:3000/test/input-data/protocol/empty.gpml

**Comment by khanspers** [comment]
Yes, we should set a maximum zoom. Not sure what exactly the zoom factor is calculated though.

**Comment by ariutta** [comment]
Our svg-pan-zoom library has options for fitting everything in the screen,
which is good for most pathways. Should we set the maximum zoom such that
the height of the pathway title, organism, etc. section is no more than 25%
of the full diagram height?

**Comment by khanspers** [comment]
Sure, or even less than that, like 15%.
