### ISSUE TITLE
Links in annotation display popup that go nowhere

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#291]
We have some linkouts that actually don't link out to anything, like for Illumina, because they don't provide a useful URL pattern.  In the display of linkouts at the bottom of the page (not pvjs) we just show the value without forming href links. But in pvjs the value is being formed as a link, a link to nowhere. Can the styling of these values be dependent on whether a URL pattern is available or not?  

Example: WP1991, SRF, Illumina (see screenshot)
![screen shot 2014-08-20 at 12 10 43 pm](https://cloud.githubusercontent.com/assets/1418193/3986793/65cc1c5a-289e-11e4-988f-05f0a7c19485.png)

**Comment by khanspers** [comment]
This has been partially addressed. The identifiers are now styled like regular text (black), but there is still an underline on hover.

**Comment by khanspers** [comment]
css needs:

.annotation-item-title:hover {
text-decoration: none;
cursor: none;
}

**Comment by khanspers** [comment]
Correcting: adds hover to a.annotation-item-text instead. See pull request.

**Comment by khanspers** [comment]
https://github.com/wikipathways/kaavio/pull/3
