### ISSUE TITLE
annotation panel linkouts should open in new tab

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#294]
I thought we fixed this before, but it's back...

1. click on a datanode to pull up the annotation panel
2. click on an xref link

expected behavior: open in new tab
observed behavior: current tab takes you away from wikipathways

**Comment by AlexanderPico** [comment]
I guess this should be in Kavio, not pvjs, but anyways...

It looks like line 187 is trying to do this:
https://github.com/wikipathways/kaavio/blob/master/src/annotation-panel/annotation-panel.js#L187

But couldn't this line simply be replaced with:
.attr('target', '_blank');

**Comment by ariutta** [comment]
It's fixed in the current master. You can see it at pvjs.wikipathways.org.

We just haven't pushed it to production on WP yet.

----- Original Message -----

**Comment by AlexanderPico** [comment]
Thanks!
