### ISSUE TITLE
Annotation details panel for Pathway DataNodes

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#296]
Egon requested that DataNodes of type Pathway have annotation details panels. @egonw, could you specify what should be in the panel? For Metabolites, etc., the panel displays info from BridgeDb, but BridgeDb doesn't have linkouts to other pathway databases, does it?

**Comment by ariutta** [comment]
To clarify, Pathway DataNodes do have annotation details panels, but only when they have an Xref. For example, [WP1403](http://wikipathways.org/index.php/Pathway:WP1403) has five pathways on the lower left, but only the ones with Xrefs have details panels.

**Comment by egonw** [comment]
Oh, do they... sorry, I missed that, and was in fact what I had in mind. So, from my perspective this issue can be closed then.
