### ISSUE TITLE
remove whitespace from Xref IDs before mapping and in linking out

### ISSUE THREAD

**Issue by egonw** [wikipathways/pvjs#297]
I just noticed that mapping and linking does not work if an Xref contains whitespace (quite common) in the GPML. Example "Dihydrofolate" in WP176... clicking on it show no mappings in the popup box and the link out has a space in the URL...

**Comment by AlexanderPico** [comment]
Good catch. Since Xrefs should *never* have spaces, I think we could approach this issue with two, parallel solutions:

1. In view mode, pvjs should trim() the xref whenever it reads one.
2. In edit mode, pvjs should trim() the xref whenever it writes one.

Anders, can you do this?

**Comment by ariutta** [comment]
Yes, that's doable. How about a non-pvjs part 3: writing a script to remove spaces from all existing Xrefs?

**Comment by mkutmon** [comment]
I just fixed it in PV as well. I can also write a script to fix it if
needed.

On Fri, May 1, 2015 at 9:36 PM, Anders Riutta <notifications@github.com>
wrote:

> Yes, that's doable. How about a non-pvjs part 3: writing a script to
> remove spaces from all existing Xrefs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wikipathways/pvjs/issues/297#issuecomment-98213947>.
>



-- 



*-----------------------------------------------Martina Summer-Kutmon,
PhDemail: mkutmon@gmail.com <mkutmon@gmail.com>skype: mkutmon*

**Comment by egonw** [comment]
Tina, while add it... have it look and fix those &x10; and &xa; thingies as well?

I can make a check for all escaped characters, if that is helpful...
