### ISSUE TITLE
Non working demos ?

### ISSUE THREAD

**Issue by kevintc** [wikipathways/pvjs#298]
Hi !

I'm trying to use pvjs with jQuery, tried the code snippet described on the front page of the wiki but I'm getting stuck with an error, the console output is the following :
TypeError: $(...).pvjs is not a function index.html:11

My code :

![image](https://cloud.githubusercontent.com/assets/7962247/7473275/528ff956-f33a-11e4-88a8-75fea041a21f.png)

I also tried to include it in a $(function() { } ); but with no success.

How can I make it work ?

I also tried to use the Highligther but the demo page outputs a weird result :
![image](https://cloud.githubusercontent.com/assets/7962247/7473341/c208439c-f33a-11e4-9369-313a5f8e5f7b.png)

My goal is to load a gpml file provided by a php script with the ability to higlight specific nodes using js calls. Is it possible ?

**Comment by ariutta** [comment]
Hi @kevintc. What you're doing should definitely be possible. I'm looking into it right now to see where the error is coming from.

**Comment by ariutta** [comment]
OK, I figured out where the error is. Next I'll rebuild and release a fixed version.

**Comment by ariutta** [comment]
I updated a few settings, so it should work again. Try following [this example](https://github.com/wikipathways/pvjs/blob/a3f3b015217a37b0ccfcded6d529f0df551127ee/demo/jquery-demo.html#L34) and let me know how it goes. Notice there are two ways to do the highlighting. The simpler way is to just pass in a `highlights` option, but you can also follow the more complex way like `pathInstance1.highlight(...)`.

**Comment by kevintc** [comment]
Thank you, I got the first instance working but the highlight after render is not working (see example below).

Is there a way to pass a list of items to be highlighted or is it only one at a time ?

![image](https://cloud.githubusercontent.com/assets/7962247/7489196/810fc88e-f3d4-11e4-9959-4ba551a8e610.png)

**Comment by ariutta** [comment]
Yes, you can pass in any number of highlights initially:

```js
      highlights: [
        {
          selector: 'ATFS-1',
          backgroundColor: 'yellow',
          borderColor: 'blue',
        },
        {
          selector: 'ABC123',
          backgroundColor: 'white',
          borderColor: 'red',
        },
        {
          selector: 'XYZ987',
          backgroundColor: 'green',
          borderColor: 'yellow',
        }
      ]
```

I'll try looking into why the highlight after render is not working.

**Comment by ariutta** [comment]
The highlight after render should be working in v2.3.1. Let me know if anything else comes up.

**Comment by kevintc** [comment]
I loaded the new version (along with the .map file) into my pvjs folder, tried to use it without changing the code and I'm getting a blank page, the pathway doesn't render anymore.
Am I missing some libraries ?
I also tried with the libraries listed under  in the "full_demo.html" file. No success either...

```html
  <body>
    <h1>Pvjs Diagram Instance 1: WP525</h1>
    <div id="wikipathways-pvjs" style="width: 800px; height: 570px; border: 1px solid #ccc;">
      <img alt="WP525 Biological Pathway"
        src="http://www.wikipathways.org//wpi/wpi.php?action=downloadFile&type=png&pwTitle=Pathway:WP525">
    </div>

    <script src="./lib/pvjs/pvjs-dev-polyfills.bundle.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="./lib/pvjs/pvjs-2.3.1.bundle.min.js"></script>
    <script>
    /* *******************
    /* Load pvjs
    /* *******************/
    $('#wikipathways-pvjs').pvjs({
      fitToContainer: true,
      manualRender: true,
      sourceData: [
        // at least one item required
        {
          uri:'data/WP525_78459.gpml',
          fileType:'gpml' // generally will correspond to filename extension
        }
      ],
      displayErrors: true,
      displayWarnings: true,
      highlights: [
        {
          selector: 'ATFS-1',
          backgroundColor: 'yellow',
          borderColor: 'blue',
        }
      ]
    });

    // Get first element from array of instances
    var pathInstance = $('#wikipathways-pvjs').pvjs('get').pop();
    console.log(pathInstance)

    // Load notification plugin

    // Call after render
    pathInstance.on('rendered', function(){
      pathInstance.highlight('GCN-2', null, {backgroundColor: 'gray'});
    });

    // Call renderer
    pathInstance.render();
    </script>

</body>
```

**Comment by ariutta** [comment]
That's odd - let me check...

**Comment by ariutta** [comment]
OK, I have these two demos tested and running online:

http://wikipathways.github.io/pvjs/jquery-demos/highlighting-basic.html
http://wikipathways.github.io/pvjs/jquery-demos/highlighting-advanced.html

All the files you'll need are listed in each of those two demos.

I noticed some delays from the Cloudflare CDN, which I'm relying on for some of the scripts in the demos. You could host the scripts elsewhere if that issue affects you too.

If you have any other questions, I'll be available this coming Tuesday. Good luck!

**Comment by kevintc** [comment]
Great work ! I will test that :) thank you a lot !

**Comment by kevintc** [comment]
It's working, thanks :)
Is there any way to reset the highlights and give the pathway another array of nodes ? (else I will clear my div and fill it again using a php script)

**Comment by ariutta** [comment]
Glad it's working now :) Once the pathway is rendered, you should be able control the highlighting as shown in the [advanced example](https://github.com/wikipathways/pvjs/blob/master/demo/jquery-demos/highlighting-advanced.html#L67). The demo shows how to use the `highlight` method to add new highlights. You can remove specific highlights one-by-one with the `attenuate` method, like this:

```js
pathInstance1.attenuate('PHB-2');
```

You may need to specify that the highlighting was preset to remove it:

```js
pathInstance1.attenuate('PHB-2', 'preset');
```

At present, we don't have a documented method to remove all highlights. Would that be useful?

Here's the source code for the highlighter: https://github.com/wikipathways/kaavio/blob/master/lib/highlighter/highlighter.js

**Comment by ariutta** [comment]
I'm open to suggestions for the API for the highlighter. Does adding the highlights one-by-one work for you, or would you like to be able to add an array after the pathway was rendered? Right now, the initial array is handled like this:

https://github.com/wikipathways/kaavio/blob/master/lib/diagram-renderer/diagram-component.js#L33

But there's no option for passing in an array after the pathway is rendered.

**Comment by kevintc** [comment]
Well, if I can give an array to the highlight method it could be great, something like :

```javascript
pathInstance1.highlight(['aaa', 'bbb', 'ccc'], null, {backgroundColor: 'gray'});

// maybe a global method to reset all highlights :
pathInstance1.resetHighlights();

// another method to remove highlights on specific nodes
pathInstance1.removeHighlights(['aaa', 'bbb', 'ccc']);
// could reset all gray colored items and leave the others
pathInstance1.removeHighlights(all, {backgroundColor:'gray'}); 
```

**Comment by ariutta** [comment]
Thanks for the feedback. Since there's already an 'attenuate' method, it'll be less confusing to stick with that instead of 'removeHighlights'. What do you think about these methods:

// global method to remove all highlights - any preference for one of the following?
1) pathInstance1.attenuate(); // notice no arguments
2) pathInstance1.attenuateAll();
3) pathInstance1.clear();

// another method to remove highlights on a set of specific nodes
pathInstance1.attenuate(['aaa', 'bbb', 'ccc']);

For the method to reset by style, this might be better in a plugin in order to avoid making the pvjs core even larger than it already is.

I will add these as feature requests for the highlighter API, to be included in an upcoming release.

----- Original Message -----

**Comment by kevintc** [comment]
I would rather go with the 2nd proposition : attenuateAll(), as attenuate() without arguments could be confusing.

pathInstance1.highlight(['aaa', 'bbb', 'ccc'], null, {backgroundColor: 'gray'});
pathInstance1.attenuate(['aaa', 'bbb', 'ccc']);
> that seems logic and should be really usefull for me :)

**Comment by ariutta** [comment]
OK, I added these two in release 2.4.0:

```js
pathInstance1.highlight(['aaa', 'bbb', 'ccc'], null, {backgroundColor: 'gray'});
pathInstance1.attenuate(['aaa', 'bbb', 'ccc']);
```

In digging into the codebase further, I saw that the original author of the highlighter had implemented `attenuate() ` to remove highlighting from all elements with no specified group. To remove all highlighting, please check out the attenuate calls in this example:

http://wikipathways.github.io/pvjs/jquery-demos/highlighting-advanced.html#/editor/disabled

I will hold the feature request for `attenuateAll` for a future release. When implemented, it will remove highlighting from all elements, regardless of whether they have a specified group.

Let me know if you see any bugs/issues with 2.4.0. Thanks!
