### ISSUE TITLE
Skip pathway resizing when Quick Edit is started

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#299]
Right now, when Quick Edit is opened, the pathway is resized to fit in the remaining space, reducing the size. For large pathways, this makes it hard to see the details and even in some cases to click on individual data nodes without zooming. A suggestion is to not have the pathway resize, but instead open the Quick Edit bar on top of the lower part of the pathway.

For example, if I am looking at a pathway and have already zoomed in to a part of interest, then decide to start QE, the focus is lost and the pathway is zoomed all the way out, plus more, so the user would need to redo the steps of finding the relevant part of the pathway.

**Comment by AlexanderPico** [comment]
We looked into this already. Can't do it. Pvjs only has control over the inner window and not the lower portion that is php.  We are, however, planning to resize the window overall. It's just an artifact of a recent change, in fact, that it's so short.
