### ISSUE TITLE
Awkward spacing in Quick Edit button 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#300]
The Quick Edit button has some awkward spacing, but after looking at the source I'm not sure its fixable. Reporting it anyway. 

The space between "Quick" and "Edit" seems a little too large, which is exaggerated by the lack of space  between the glyph (^) and the first word. The css font style is normal, and I don't know how to fix the space between the words (which would be ideal). I guess we could add a space after the glyph (see below), but that seems hacky and I'm not sure it looks better. A minor issue, it just has a slightly odd look to it. Documenting it here for reference. 

Suggested fix (space inserted before Quick), and screenshot of the button after the fix:
<span aria-hidden="true" class="glyphicon glyphicon-chevron-up">Quick Edit</span>
::before
" Quick Edit"
</span>
 
![screen shot 2015-05-05 at 12 45 34 pm](https://cloud.githubusercontent.com/assets/1442197/7481431/ad274614-f324-11e4-801b-0d934de18ccb.png)

**Comment by AlexanderPico** [comment]
It is covered in the span class that specified the glyphicon settings, like font-family "Glyph Haflings" or some such nonsense. Basically, it was in wingding font :)

We put the text in a separate span and the rendering is solved.
https://github.com/wikipathways/kaavio/blob/8cab26572ea529b5fdf8f5c11450eaaf9da81b93/lib/editor/editor-open-button.js#L57
