### ISSUE TITLE
Resizing browser window in Edit mode causes resizing of the pathway 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#301]
Browser: Chrome 42.0.2311.90 (64-bit)

In Edit mode, if I resize the browser window, the pathway gets zoomed in to the point where only the upper left portion of the pathway is visible. See examples below. 
This seems to happen only the first time the browser window is resized. After the first time, if I reset the zoom level of the pathway and try again, it doesn't resize the pathway at all. If I close Edit mode and try again, the resizing issues comes back.

Before:
![screen shot 2015-05-05 at 12 53 08 pm](https://cloud.githubusercontent.com/assets/1442197/7481570/bf6872d4-f325-11e4-8cbd-d2707407e7ad.png)

After:
![screen shot 2015-05-05 at 12 53 27 pm](https://cloud.githubusercontent.com/assets/1442197/7481574/c648aae2-f325-11e4-938b-e8b211df6251.png)

**Comment by AlexanderPico** [comment]
Current workaround: shift css so grab corner is not accessible. Ideally, we could just disable resize for this release and revisit resize in future full-feature editor release.

**Comment by AlexanderPico** [comment]
Ah, removed overflow:hidden from container and that removed resize option
