### ISSUE TITLE
pvjs freezes when clicking on non-data node objects in edit mode

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#303]
It seems pvjs freezes (after first slowing down) when clicking on non-data node objects in edit mode. After successfully clicking on several data nodes, selecting interactions is problematic. The first few work, but then selection starts getting slow and eventually freezes up completely. 

Tried this with two small pathways that don't have a lot of graphics: WP528 and WP197.

Some of the interactions selected were anchored, don't know if this makes a difference.

**Comment by ariutta** [comment]
Interesting - I think that's what Alerx ran into as well.

----- Original Message -----

**Comment by khanspers** [comment]
The same thing happens with graphical objects. Try with http://pvjs.wikipathways.org/index.php/Pathway:WP405. Continued clicking on the colored ovals causes slow-down followed by complete freeze.
