### ISSUE TITLE
firefox: text labels disappear after zooming

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/pvjs#304]
This happened on Windows and Linux. Text labels disappear when you zoom in or out in the viewer in Firefox.

**Comment by ariutta** [comment]
Does it happen also at pvjs.wikipathways.org? I think it's fixed, as per issue #253, but the latest code isn't live at www.wikipathways.org.

**Comment by mkutmon** [comment]
Sorry haven't checked that yet. I only did a demo today and saw it. I will check again.

**Comment by khanspers** [comment]
@mkutmon Can you check again? Going through and closing out bugs.

**Comment by khanspers** [comment]
No longer relevant as per Tina.
