### ISSUE TITLE
Need timeout on xref lookup for viewer annotation panels

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#306]
Clicking on a data node that is annotated with an identifier system that is not supported in bridgedb causes the annotation panel to perpetually show the loading wheel. Try it out in this pathway by clicking on "Old pubchem Db id":

http://www.wikipathways.org/index.php/Pathway:WP2582

**Comment by khanspers** [comment]
This is more of a problem on plant pathways (and maybe others?) were many data nodes are annotated with EC numbers and Gramene plant ids. Just to clarify, the nodes are annotated (correctly from the ones I checked), and linkouts work, but the identifier is NOT in bridgedb. So the spinning wheel makes it look like the nodes (and pathway) are a lot more broken they they actually are.

Examples:
http://pvjs.wikipathways.org/index.php/Pathway:WP2208
http://pvjs.wikipathways.org/index.php/Pathway:WP2211
http://pvjs.wikipathways.org/index.php/Pathway:WP2199

**Comment by AlexanderPico** [comment]
Anders, I know you're avoiding timeouts in other parts of the code, but I wonder if this is a reasonable place for one?  In general, if nothing is returned for the annotation panel (for whatever reason), we should at some point just display "no results" or blank or whatever, rather than keep the spinner up.

**Comment by khanspers** [comment]
It's working on the main site, where it just displays the annotation ,but without the bridgedb cross-refs. See attached. So this is a regression bug I think.
![screen shot 2015-06-23 at 1 57 55 pm](https://cloud.githubusercontent.com/assets/1442197/8317111/09d1d788-19b0-11e5-85c9-159cf19c6ef9.png)

**Comment by khanspers** [comment]
Labeling this as bug since it is working on the viewer on the main site.

**Comment by AlexanderPico** [comment]
When you search for an xref that's not there, e.g., "asdfgh", the spinner stays up forever. Let's add a 5 second timeout here and return a modal with the content: "No results found"

**Comment by khanspers** [comment]
Just to be clear, the original issue here has to do with the popup annotation panel that appears when a node is selected in the viewer, not search in QuickEdit. See screenshot above.

**Comment by AlexanderPico** [comment]
You're right! I'll start a new bug for this one... #338

Both bugs are about handling a "no result" from a bridgedb query, but THIS bug is for the case of the annotation panel. See examples above or any pathway node, e.g., http://pvjs.wikipathways.org/index.php/Pathway:WP1403. 

This is a regression error. It works fine on live site.

**Comment by ariutta** [comment]
Does the annotation panel look correct in the screen shots for the following three conditions?

If BridgeDb is not available and we don't know the entity's datasource:
![a-p-no-bridgedb-no-db](https://cloud.githubusercontent.com/assets/1296771/8534881/99a66ff0-23f5-11e5-8442-b1ed05864e34.png)

If BridgeDb is not available but we do know the entity's datasource:
![a-p-no-bridgedb](https://cloud.githubusercontent.com/assets/1296771/8534898/c44f91e6-23f5-11e5-967c-c092b0e0fe2d.png)

If BridgeDb is available:
![a-p-bridgedb](https://cloud.githubusercontent.com/assets/1296771/8534903/ce7b704a-23f5-11e5-921f-6a86bcda3137.png)

**Comment by AlexanderPico** [comment]
Yes, if "Identifier/Label" is replaced with the known datasource in case 2. In case 1, it should just say "Identifier".  If no identifier is provided, then it shouldn't show anything: no label, no "find other pathways...", etc.

**Comment by ariutta** [comment]
Updated, with new conditions:

If BridgeDb is not available and we only have the label:
![a-p-no-bridgedb-no-db](https://cloud.githubusercontent.com/assets/1296771/8534881/99a66ff0-23f5-11e5-8442-b1ed05864e34.png)

If BridgeDb is not available, we don't know the datasource or identifier, but we do somehow have the label and the uri for the linkout:
![a-p-no-bridgedb](https://cloud.githubusercontent.com/assets/1296771/8535129/b48e56d2-23f7-11e5-8578-a831f44c4303.png)

If BridgeDb is available:
![a-p-bridgedb](https://cloud.githubusercontent.com/assets/1296771/8534903/ce7b704a-23f5-11e5-921f-6a86bcda3137.png)

For a cellular component:
![a-p-cellular-component](https://cloud.githubusercontent.com/assets/1296771/8535363/00242a02-23fa-11e5-8efd-8bfae8746955.png)

**Comment by ariutta** [comment]
Uploaded 2.4.33 to pvjs.wikipathways.org with the annotation panels rendering as described above.

----- Original Message -----

**Comment by ariutta** [comment]
Changed the look for the case when BridgeDb not available and we only have the label
![a-p-no-bridgedb-no-db](https://cloud.githubusercontent.com/assets/1296771/8535726/5fde920e-23fd-11e5-9dd7-e4f8e5aa2bbf.png)
:

**Comment by ariutta** [comment]
Use 2.4.34 to see the version with the latest handling of the annotation panel.

----- Original Message -----
