### ISSUE TITLE
linebreak interferes with highlight gene in pathways

### ISSUE THREAD

**Issue by acivansteen** [wikipathways/pvjs#309]
In a pathway (1) where a gene (2) contains a linebreak in the label, the highlight gene function does not work. The search bar removes the linebreak and does not find the gene and highlight it. 

1.  http://wikipathways.org/index.php/Pathway:WP2670
2. HTR3D [plasmamembrane]

**Comment by ariutta** [comment]
Thanks for finding this. I'll take a look at solving it for the next release.

**Comment by khanspers** [comment]
I can't replicate this. Tried by introducing some line breaks in the Sandbox pathway and nodes are still found. Closing this.
