### ISSUE TITLE
Metabolite annotation - wrong datasource selected

### ISSUE THREAD

**Issue by mkutmon** [wikipathways/pvjs#310]
When I search for glucose, I get a lot of HMDB identifiers suggested:
![selection_045](https://cloud.githubusercontent.com/assets/2158343/7970156/70b8bbb6-0a3c-11e5-92d0-091db7a4c6ae.png)

When I then select one of the xrefs, the identifier and label is filled in correctly but the datasource not. I tried several time, and different datasources were selected (once KEGG Reaction and once MGI).
![selection_046](https://cloud.githubusercontent.com/assets/2158343/7970198/a9d8e7f4-0a3c-11e5-8a69-51d719f811df.png)

**Comment by ariutta** [comment]
Alex, did we figure out whether BridgeDb was returning the expected data for metabolites?

----- Original Message -----

**Comment by AlexanderPico** [comment]
Well, it must be since it's populating the table with "HMDB." I presume you grab the info from this table to then choose the pulldown selections.  So, I suspect the issue is there...

**Comment by AlexanderPico** [comment]
Ah, all metabolite datasources are missing from the pulldown list. We just need to include them in our initial query. That should fix it...
