### ISSUE TITLE
Editor: trouble selecting nodes in WP2853.

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#311]
Some of the nodes are selectable, but many others are not, even if they have an Xref. It could be because there's a non-DataNode overlayed above the DataNode.

http://pvjs.wikipathways.org/index.php/Pathway:WP2853#/editor/open

**Comment by AlexanderPico** [comment]
Datanode "Type" is missing from many nodes. Sampling a few, this seems to correlate with nodes that can't be selected.

**Comment by AlexanderPico** [comment]
Fixed by manually adding Type information to deficient datanodes. I fixed the live copy at wikipathways, so the one at pvjs will still appear broken. 

Reopen if other cases are found, i.e., if this isn't an isolated curation issue
