### ISSUE TITLE
editor open (yet hidden) when url says disabled

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#314]
If you navigate to http://pvjs.wikipathways.org/index.php/Pathway:WP4#/editor/disabled while logged on then when you can click on pathway elements you see editor highlighting even though the editor is hidden. Appears to user like annotation panel is broken.

**Comment by ariutta** [comment]
Is the desired behavior for the `disabled` state to be the same as for the `closed` state, except that the "Quick Edit" button is not visible? E.g., when an element is selected, it is highlighted and the details panel opens.

**Comment by AlexanderPico** [comment]
When a user is not logged in to wikipathways and they go to a pathway page (i.e., editor/disabled), they should be able to interact with the viewer and details panels, right?  Maybe I'm missing something... what did you intend for the disabled state?

**Comment by ariutta** [comment]
Yes, they should. The details panel not opening is a bug. But is the highlighting OK?

**Comment by AlexanderPico** [comment]
Fine with me. I only called it "editor highlighting" because the behavior without the panel is the same now I guess.

**Comment by AlexanderPico** [comment]
Ok. We should try not exposing editor in URL and verify that states still behave.
