### ISSUE TITLE
Suggestion: Move Quick Edit tabs to the left

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#315]
The two tabs for Annotation and Properties are indented which makes for an odd look. The area with grey background extends to the left of the horizontal line border under the tabs, which looks weird since this is not the case on the right side and the Close button is right-aligned. 

Proposal: Move the tabs all the way to the left. See attached for before and after. 

If agreed I can submit a pull request.
![screen shot 2015-06-04 at 12 41 29 pm](https://cloud.githubusercontent.com/assets/1442197/7992970/d6a5b5ac-0ab7-11e5-9e96-84f2d9dea85f.png)
![screen shot 2015-06-04 at 12 41 23 pm](https://cloud.githubusercontent.com/assets/1442197/7992971/d6a9b4ea-0ab7-11e5-9ac8-d88e44f5e572.png)

**Comment by khanspers** [comment]
So the images got reversed, it is actually "after" followed by "before".

**Comment by AlexanderPico** [comment]
Nice. I like it.

**Comment by khanspers** [comment]
Anders, in my local web server version of this, I don't see the gap at the left (see attached). Any ideas why? 
I can go ahead and make the pull request anyway, based on the behavior at pvjs.wikipathways.org. Let me know what you prefer.
![screen shot 2015-06-04 at 3 53 49 pm](https://cloud.githubusercontent.com/assets/1442197/7999377/ee200380-0afe-11e5-9155-9360ba8e8f61.png)

**Comment by ariutta** [comment]
I think the CSS formatting from MediaWiki affects it somehow. Sure, you can make a pull request. If it isn't what we want, we can always change it. I'll be able to deploy it again Monday.

----- Original Message -----

**Comment by khanspers** [comment]
OK, made a change in stripped-bootstrap.css in kaavio. See pull request.

**Comment by ariutta** [comment]
I think the pull request is now merged and redeployed, but it still appears to be centered. Can you check it to see whether it reflects your changes?
http://pvjs.wikipathways.org/index.php/Pathway:WP4

**Comment by AlexanderPico** [comment]
Tabs have been shifted left. Looks better.

**Comment by khanspers** [comment]
I see the same as Alex, it reflects my changes. Tabs are left-aligned.

**Comment by ariutta** [comment]
OK, I see it now. Great! Is this ready to close?
