### ISSUE TITLE
TypeError for WP2059

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#316]
http://pvjs.wikipathways.org/index.php/Pathway:WP2059
http://pvjs.wikipathways.org/index.php/Pathway:WP1772

These pathway are not showing up, blank container. The console shows this error (in addition to "normal" errors):

Uncaught TypeError: Cannot read property 'indexOf' of undefined

**Comment by ariutta** [comment]
I think I know what's causing this, and it might be related to several other issues. I'll be able to dig into it next week.
