### ISSUE TITLE
front page thumbnail is triggering pathwayThumb.php code

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#317]
not technically in pvjs, but due to changes to accommodate pvjs...

The wacky front page is due to pwThumb div and thumbinner class being inserted into the Pathway of the Day feature.  Any ideas on how to distinguish between a front page feature and the Pathway Pages?  This is also clobbering thumbnails in each of the Portal pages.

Attached screenshot of inspected code...

![screen shot 2015-06-04 at 5 33 25 pm](https://cloud.githubusercontent.com/assets/1418193/7997345/494d98e0-0ae0-11e5-9257-2e39086cf0fe.png)

**Comment by AlexanderPico** [comment]
The makeThumbLinkObj() function had been completely overwritten, affecting both pathway images and ANY thumbnail of a pathway on the site.  I restored the old method and forked the call to either either go there or, in the case of pathway pages, go to a NEW function called makePvjsObj().

**Comment by ariutta** [comment]
It seems like displaying a pathway is kind of its own component, which currently appears to be in pathwayThumb.php. I'm not really sure with the PHP codebase, but maybe the smarter thing to do could be to revert pathwayThumb.php to just display a small thumbnail, and a new page could be responsible for displaying a full-sized version of the pathway.

**Comment by ariutta** [comment]
Ha, looks like we're on the same wavelength!

**Comment by ariutta** [comment]
What about the widget?

**Comment by AlexanderPico** [comment]
widgets are iframes, so they don't touch this code, as far as I can tell...

**Comment by ariutta** [comment]
I think the widget gets pvjs the same way the pathway page does.

**Comment by AlexanderPico** [comment]
Well, they are working...

**Comment by ariutta** [comment]
OK, so I had a chance to look at PathwayWidget.php, and it appears it depends on PathwayViewer.php to get the JS dependencies. It does not appear to depend on pathwayThumb.php, but it does seem to duplicate at least some functionality from the `makePvjsObj()` function.

**Comment by AlexanderPico** [comment]
What's the concern with PathwayWidget? It's working properly, right?

**Comment by ariutta** [comment]
The relationship between pathwayThumb.php, PathwayViewer.php and PathwayWidget.php is confusing to me. If I need to update any of them in a few months, it's going to be tough, so I'm trying to document it now.

* wpi/PathwayWidget.php creates a pathway viewer.
* wpi/extensions/pathwayThumb.php creates both a thumbnail and a pathway viewer/editor.
* wpi/extensions/PathwayViewer/PathwayViewer.php creates a list of JS dependencies and sets the active pathway version.

**Comment by AlexanderPico** [comment]
Indeed. Those are confusing and have changes a few times. Good idea!
