### ISSUE TITLE
Datanode selection in FF

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#318]
Can't select datanodes in Firefox when inside a group or compartment. The shapes seem to be "on top" and block datanode selection.

**Comment by ariutta** [comment]
See sandbox pathway.

**Comment by khanspers** [comment]
Just foudn a pathway on the main site that has this issue too: http://www.wikipathways.org/index.php/Pathway:WP2944
Try selecting any nodes in the upper left box (AHK1-5)

**Comment by AlexanderPico** [comment]
Unlike sandbox example, this one is buggy is both chrome and ff. The original bug was for observations in ff that worked just fine in chrome. I wonder if it's a different bug...?

**Comment by khanspers** [comment]
moving the AHK example to a new issue......

**Comment by ariutta** [comment]
Closed via 47b583f70b6e3583f0bc55bd8219a006350d9e95
