### ISSUE TITLE
Selection of shapes does not update color picker

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#319]
Right now you can select a shape (including cellular components and groups) and change their color via the Properties tab (cool), but the color picker does not get updated with the current shape color when it's first selected.

Steps to reproduce:
1. Select a shape or group.
2. Change to red via color picker in Properties tab.
3. Select off of group or on another group.
4. Select the red shape or group.

Expected behavior: the color picker should show a red color chip.
Observed bug: the color picker shows a black color chip.

**Comment by khanspers** [comment]
Also true for interactions.

**Comment by AlexanderPico** [comment]
KH: This only changes the outline of the shape though, not the fill color. This is confusing for pathways with shapes that have fill color. We should disable changing the color of shapes until we can support both fill and outline color.

http://pvjs.wikipathways.org/index.php/Pathway:WP2848

**Comment by AlexanderPico** [comment]
As far as I can tell, a method like this:
https://github.com/wikipathways/kaavio-editor/blob/master/lib/editor-tabs-component/tabs/annotation-tab/annotation-tab.js#L51

Needs to be added here:
https://github.com/wikipathways/kaavio-editor/blob/master/lib/editor-tabs-component/tabs/properties-tab/properties-tab.js#L37

But it's slightly beyond my js skills to attempt that...

**Comment by ariutta** [comment]
Closed in 755454b21b330afd5fa59045f2b2a4cd49132bec
