### ISSUE TITLE
Changing color of shapes only changes outline color

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#320]
As noted in https://github.com/wikipathways/pvjs/issues/319, it is possible to change the color of shapes. This only changes the outline of the shape though, not the fill color. This is confusing for pathways with shapes that have fill color. We should disable changing the color of shapes until we can support both fill and outline color.

http://pvjs.wikipathways.org/index.php/Pathway:WP2848

**Comment by khanspers** [comment]
The same is true for interactions, only the line color is changed, not the arrow or other end symbol.

**Comment by AlexanderPico** [comment]
combined with #319
