### ISSUE TITLE
Add notification of successful/failed save events as a banner

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#321]
The notification system is not displaying. We might want to use this to notify user of successful and failed saves. Alternatively, we might just use http://getbootstrap.com/components/#alerts for these simple cases...

**Comment by ariutta** [comment]
It actually works -- it's just not set to display errors with parsing GPML. Do you want it to display an error if the GPML, for example, is using an outdated version?

**Comment by khanspers** [comment]
@AlexanderPico: Is this still an issue?

**Comment by AlexanderPico** [comment]
Well, I can't test this again until updatePathway is fixed, but as far as I know this is still an issue. I've changed the title, though, to be more specific.  It's a suggestion to notify when save succeeds and fails. It's NOT a suggestion to have all errors displayed. I'd rather have these off, in fact.
