### ISSUE TITLE
success notifications not showing [was: pvjs is not defined]

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#323]
Trying to trigger notifications, but not sure how to reference pvjs here...
https://github.com/wikipathways/pvjs/blob/master/lib/editor/editor.js#L188

Can you update the four reference between lines 188 and 210, and then rebuild?

**Comment by ariutta** [comment]
Done. 2.4.21.

----- Original Message -----

**Comment by ariutta** [comment]
Can we close this?

**Comment by khanspers** [comment]
@AlexanderPico: Can we close this? I don't know how to test it.
