### ISSUE TITLE
Pathway view doesn't load unless logged in

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#324]
Pathways are not loading when not logged in. The viewer displays a large spinning wheel and the pathway never loads.

**Comment by ariutta** [comment]
Do you have an example pathway?

**Comment by khanspers** [comment]
I can't get the view for any pathway unless logged in.
Try these:
http://pvjs.wikipathways.org/index.php/Pathway:WP2888  (pathway of the day today)
http://pvjs.wikipathways.org/index.php/Pathway:WP554

**Comment by AlexanderPico** [comment]
The PHP code seems to be working properly. I think this is related to changes to the handling of "disabled" vs "closed" in the pvjs code.  This line seems suspicious to me...

https://github.com/wikipathways/kaavio-editor/blob/master/lib/main.js#L101

**Comment by ariutta** [comment]
It was actually here: https://github.com/wikipathways/pvjs/blob/master/lib/main.js#L92

**Comment by ariutta** [comment]
Should be fixed in 2.4.28.

**Comment by AlexanderPico** [comment]
Hmm... not fixed yet.

**Comment by ariutta** [comment]
It's the footer about line 250 of kaavio/lib/main.js. I'll build it again Wed.

----- Original Message -----

**Comment by ariutta** [comment]
Fixed in 2.4.30.
