### ISSUE TITLE
Search button and input field are misaligned

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#325]
See attached
![screen shot 2015-06-15 at 4 54 00 pm](https://cloud.githubusercontent.com/assets/1442197/8173227/31cfb5fc-137f-11e5-9975-464bbddc5622.png)

**Comment by khanspers** [comment]
AP has a solution for this. Punting for now.

**Comment by AlexanderPico** [comment]
It's input-group-btn:last-child...
https://github.com/wikipathways/kaavio/blob/master/lib/stripped-bootstrap.css#L271

changing margin-top to -2px will bump it up to same level

Went back and forth on this setting earlier though, so not sure if that's the right setting given all other variables. Was waiting for other css changes to settle...

**Comment by AlexanderPico** [comment]
For example, it looks like THIS in Firefox right now, so....

![screen shot 2015-06-23 at 1 50 43 pm](https://cloud.githubusercontent.com/assets/1418193/8316941/f103a7e6-19ae-11e5-9004-5afe529df55c.png)

**Comment by khanspers** [comment]
It now looks ok in FF and Chrome, but with a slight offset in Safari:
<img width="290" alt="screen shot 2015-12-09 at 2 35 58 pm" src="https://cloud.githubusercontent.com/assets/1442197/11701061/434b5a32-9e82-11e5-961c-ea99ecf32536.png">

**Comment by khanspers** [comment]
Closing this since it works in Chrome, FF and only a slight offset in Safari.
