### ISSUE TITLE
Data node search doesn't work

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#326]
Data nodes search doesn't produce any results. Tried a variety of well-known gene that should be in the database. The search results panel never appears, and on the first search (not subsequent), there is a pale yellow banner at the top of the browser window see attached.
![screen shot 2015-06-16 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/1442197/8196171/cc72ffba-143d-11e5-99b2-741c2482daaa.png)

**Comment by ariutta** [comment]
This is regression error. Should be straightforward to fix.
