### ISSUE TITLE
Data node type is not centered in data node panel

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#328]
The entry for data node type in the data node panel is not centered, it is offset to the left. Note that this is not the case on the main site, so this is a new bug. See attached. 
Nothing obvious in the css, will keep digging.

![screen shot 2015-06-16 at 4 23 26 pm](https://cloud.githubusercontent.com/assets/1442197/8196757/2b053ab0-1444-11e5-81e5-2da74da2afd6.png)

**Comment by khanspers** [comment]
Now observed on wikipathways.org.

**Comment by ariutta** [comment]
This might be related to the change where we replaced the magnifying glass
with the text "Find other pathways containing: xyz" (at the bottom).

**Comment by khanspers** [comment]
Added padding-left of the same size as the width of the close icon. I think the more correct way to fix this is to make the description its own div, and control the layout with display: block.

**Comment by khanspers** [comment]
https://github.com/wikipathways/kaavio/pull/3
