### ISSUE TITLE
Sequential saving of edits is broken

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#331]
Here's what happens: I make a change in QuickEdit, the Close button changes to Save and Close as expected, and I can close out of the editor using the button and have the changes saved. The next time I open QuickEdit, the button says Close as expected, I make a change, which triggers the button to change to Save and Close, I close out of the editor and it looks like everything worked. However, there is an error message at the top of the browser window (attached), and the next time (third time now) I open QuickEdit, the button displays Save and Close, without any changes being made, indicating that the previous edit was not saved. And if I refresh the browser, the last edit is indeed not saved.

Try this on http://pvjs.wikipathways.org/index.php/Pathway:WP1:
1. Open QuickEdit, change a gene to red color. Save and Close.
2. Open QuickEdit, change a different gene to red. Save and Close. => see error at the top of the window. 
3. Open QuickEdit.  => Note that the button still says Save and Close. Refresh the browser window, the second edit is reverted.
![screen shot 2015-06-24 at 1 42 54 pm](https://cloud.githubusercontent.com/assets/1442197/8341193/1c3707ea-1a78-11e5-8fdc-b93e13678afb.png)

**Comment by AlexanderPico** [comment]
expected behavior, given #322
