### ISSUE TITLE
Data nodes inside rectangles and elbow connector bounding boxes can't be selected

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#332]
This is observed in Chrome (and FF by Alex). 

Some data nodes inside rectangles and the bounding boxes of elbow connectors can't be selected. Examples:

http://www.wikipathways.org/index.php/Pathway:WP2944 (Try selecting any nodes in the upper left box (AHK1-5))
http://www.wikipathways.org/index.php/Pathway:WP554 (Try selecting Ang 1-9)

For the latter example, there are differences in how it works on main site and pvjs. On the main site, the node is just not selectable. In pvjs, when trying to select the node, the T-bar whose bounding box surrounds the node is selected. Interesting since interactions in general can't be selected. http://pvjs.wikipathways.org/index.php/Pathway:WP554
Maybe this information is useful somehow. Will add other examples if I find them.

**Comment by khanspers** [comment]
In the Sandbox, all nodes inside the rectangular nucleus are selectable.

**Comment by AlexanderPico** [comment]
Is this fixed? Will test when selection is restored...
