### ISSUE TITLE
modal overlay style

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#336]
I tried overriding the simple-modal-overlay css in our stripped-bootstrap.css, but that did not work. So, next I looked for the code that includes the class to add it as an inline style, but as far as I can tell, it is only in a dist file. Aren't these automatically generated though?

https://github.com/wikipathways/kaavio/blob/master/dist/kaavio-dev-dependencies.bundle.js#L1674

In the meantime, I made the change here: 
https://github.com/wikipathways/kaavio/blob/master/dist/kaavio-dev-dependencies.bundle.js#L1755
even though I suspect it will be overwritten. No idea how else to modify this class's inline style...

**Comment by AlexanderPico** [comment]
Anders directed me to inserting the style override here: https://github.com/ariutta/mithril-simple-modal/blob/master/lib/main.js#L72

Will close after testing...

**Comment by ariutta** [comment]
Can we close this?
