### ISSUE TITLE
Mitochondria color

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#339]
You can change the color of mitochondria in Pathvisio-Java, but they will always display as gray in pvjs. This is because mitochondria are rendered as an image via a data-uri. Is it worthwhile to spend time to make mitochondria able to be displayed in other colors?

**Comment by AlexanderPico** [comment]
Nope. This should wait until we figure out how we want to deal with images vs shapes vs cellular compartments. It's part of a much bigger discussion. For now, they should just be gray, most probably are anyways, so it's not an issue.
