### ISSUE TITLE
Wrong datasource name attempting to be written to GPML

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#340]
Column 1 should be used for all standardized and programmatic cases. Column 11 should ONLY be used for UI display for human reading.

Example: Column1 = UniProt-TrEMBL; Column 11 = UniProt/TrEMBL

Currently, when searching using the annotations tab, the results come back as “UniProt-TrEMBL” (col 1), but when selected, it tries to select “UniProt/TrEMBL" (col11) from the pulldown and throws an error. 
You can search for ACE2 to reproduce this error.

So, it’s correct in the results table; it’s correct in the pulldown; but it should be writing “UniProt-TrEMBL” (col 1) into the GPML.

**Comment by ariutta** [comment]
This was fixed somewhere in the integration of bridgedbjs into gpml2pvjson and kaavio-editor.
