### ISSUE TITLE
Viewer not displaying svg for old gpml versions

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#343]
The viewer is no longer displaying svg images for old gpml versions. The viewer is simply blank. See example: http://www.wikipathways.org/index.php?title=Pathway:WP1008&oldid=58816

**Comment by AlexanderPico** [comment]
pathwayThumb.php is fixed. Just need to check for valid gpml before clearing inner html of custom wikipathways-pvjs element
