### ISSUE TITLE
annotation panel sorting is not right

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#345]
Other datasources are showing up before Ensembl, such as arrays, GO and pdbs (they shouldn't) and they are mislabeled as "BioCyc" and "SUPFAM" and "NCBI Protein"

**Comment by ariutta** [comment]
Introduced in https://github.com/wikipathways/kaavio/blob/da177d01e1498a0e9026000c735c46736d098a08/lib/annotation-panel/entity-reference.js#L159

**Comment by ariutta** [comment]
Closed in https://github.com/wikipathways/kaavio/commit/6400f8095b6d3acdee2e1cc6f5b90234d967fb94
