### ISSUE TITLE
Only Entrez Gene results are returning from search

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#346]
Steps to reproduce:

1. Click on datanode and open editor
2. search for "P35" or "APC"

expected:
* hits from Ensembl, Entrez Gene and other datasources

observed:
* only hits from Entrez Gene are returned

**Comment by AlexanderPico** [comment]
Interestingly, a search for ACE2 work fine... So, maybe this is a bridgedb issue?

**Comment by khanspers** [comment]
possibly related to #350

**Comment by AlexanderPico** [comment]
closing, since the same results come from bridgedb webservice when directly queried, i.e., it's not a pvjs issue.
