### ISSUE TITLE
Data node search returns GO results for some searches

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#347]
To test:

1. Select any node. Type in "water", "glucose" or "fructose" as the search term. (These are some of the terms I tried)

Expected:
- Search results from metabolite databases (HMDB etc)

Observed:
- Several results with data source "BioCyc" and GO terms as identifiers appear.
- The expected results also appear in the list, but because of sorting, BioCyc is listed before, so the real results are sometimes obscured completely until scrolling.

**Comment by ariutta** [comment]
Closed in https://github.com/wikipathways/kaavio/commit/6400f8095b6d3acdee2e1cc6f5b90234d967fb94
