### ISSUE TITLE
Viewer: Selecting empty data nodes doesn't close the annotation panel

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#348]
To test:

1. In Sandbox, select any annotated data node, for example Catalyst Y
2. Without closing the annotation panel, select the node labeled Product.

Expected:
- The annotation panel should close, or at least get cleared out.

Observed:
- The annotation panel remains open, with the information for Catalyst Y displayed.

**Comment by ariutta** [comment]
The annotation panel will now close if you select anything in the diagram that does not have an annotation.
