### ISSUE TITLE
Only HMDB results are returned when searching for metabolites

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#350]
Only HMDB results are returned when searching for metabolites, no CAS, ChemSpider or any of the others.
Try it on any metabolite node by searching for the assigned data node label.

**Comment by AlexanderPico** [comment]
Check to see if the same results come from bridgedb webservice when directly queried. If so, then it's not a pvjs issue. I closed the other related bug for this reason.

If not, then it is a pvjs bug...

**Comment by khanspers** [comment]
So I tried bridgedb web services, but maybe I don't have the pattern right because I don't get any results. I can get results for specific metabolites when searching for the identifier, but I don't get anything from a keyword/name search:

 I tried this:

http://webservice.bridgedb.org/Human/search/Choline  (This pattern works for gene symbols)

Any ideas?

**Comment by ariutta** [comment]
We're using this pattern for the search:
http://webservice.bridgedb.org/Homo%20sapiens/attributeSearch/Choline

That only returns HMDB and Gene  Ontology, so the problem appears to be with BridgeDb.
