### ISSUE TITLE
Weird pathway zooming after page refresh (inconsistent)

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#351]
Sometimes after refreshing a page, the pathway is zoomed way out in the viewer. If the page is refreshed again, the pathway is correctly displayed with the original zoom factor. Haven't found a pattern of when this happens, it seems inconsistent.
<img width="1141" alt="screen shot 2015-07-24 at 4 57 51 pm" src="https://cloud.githubusercontent.com/assets/1442197/8887001/6092837a-3228-11e5-9efa-c6aec5541a20.png">

See attached.

**Comment by khanspers** [comment]
Actually, since the zoom controls are also shifted  this doesn't seem like a zoom issue.

**Comment by khanspers** [comment]
I see this on the main site too.

**Comment by AlexanderPico** [comment]
This has to do with WHEN svgpanzoom is called.
