### ISSUE TITLE
Issues with identifier listings in annotation panel

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#352]
1. For some data sources, there are identifiers listed (in addition to the correct ones) that are incorrect. In some cases the identifiers are a legitimate identifier, but for a different gene. In some cases the identifiers don't have the correct format at all.

Example:

On the Acetylcholine Synthesis pathway (http://pvjs.wikipathways.org/index.php/Pathway:WP528), the PDHA2 data node has the following incorrect entries:

HGNC: uc003htr.4
Entrez Gene: 8096528, 179061, 0004540731, 0001990093
Uniprot: A_14_P202299, A_14_P139780, A_23_P81018, A_14_P201083

2. Sometimes the identifer is listed more than once. See Entrez Gene 5161 for PDHA2 gene.

<img width="329" alt="screen shot 2015-07-24 at 5 30 37 pm" src="https://cloud.githubusercontent.com/assets/1442197/8887058/b36d7040-3229-11e5-9f45-4097c3b1f5a4.png">

**Comment by khanspers** [comment]
related to #345 ?

**Comment by khanspers** [comment]
Here are the bridgedb web services results for Entrez gene 5161 (which is what PDHA2 is annotated with), sorted to match the order in the annotation panel for comarison:

GO:0016624	GeneOntology
GO:0008152	GeneOntology
GO:0004739	GeneOntology
GO:0005759	GeneOntology
GO:0043231	GeneOntology
GO:0055114	GeneOntology
GO:0006099	GeneOntology
GO:0006096	GeneOntology
ENSG00000163114	Ensembl
5161	Entrez Gene
PDHA2	HGNC
ILMN_2068951	Illumina
0001990093	Illumina
0004540731	Illumina
ILMN_1665458	Illumina
NM_005390	RefSeq
NP_005381	RefSeq
Hs.131361	UniGene
M86808_at	Affy
8096528	Affy
11734083_at	Affy
33013_at	Affy
214518_at	Affy
P29803	Uniprot-TrEMBL

uc003htr.4	UCSC Genome Browser
5161	Gene Wiki
A_14_P201083	Agilent
A_14_P139780	Agilent
A_14_P202299	Agilent
A_23_P81018	Agilent
GO:0006090	GeneOntology
5161	WikiGenes
179061	OMIM

**Comment by ariutta** [comment]
Introduced in https://github.com/wikipathways/kaavio/blob/da177d01e1498a0e9026000c735c46736d098a08/lib/annotation-panel/entity-reference.js#L159

**Comment by ariutta** [comment]
Closed in https://github.com/wikipathways/kaavio/commit/6400f8095b6d3acdee2e1cc6f5b90234d967fb94
