### ISSUE TITLE
Enhancement: Sync change state with Close/Save button

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#353]
Something I encountered while testing, tracking here for future enhancement.

If a change is made to a data node, lets say a simple color change, the “Save & Close” button appears as expected. If the color change is then reverted immediately without saving, the button should go back to its “Close” state. Currently it doesn’t. Its harmless, but could be confusing to users, and could also appear buggy.

**Comment by ariutta** [comment]
For this issue specifically, it appears the Chrome color picker has a bug. The default metabolite color is "#0000ff". If you change a "#0000ff" color metabolite to another color and then try changing it back to "#0000ff" (shown in the color selector as "0000FF" as seen below), the actual value resulting from the built-in Chrome color picker appears to be "#0433ff".

![color-picker](https://cloud.githubusercontent.com/assets/1296771/8918676/69ac6924-346e-11e5-9258-3cc720730dcf.png)

**Comment by ariutta** [comment]
See https://code.google.com/p/chromium/issues/detail?id=514425

**Comment by ariutta** [comment]
Closed via 2e3875eb3af8d56af0011c722210f7418531a7c6
