### ISSUE TITLE
Issues with save state and changes to Display Name and Identifier

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#354]
A couple of issues that are probably related. The short story is that deleting only identifier or display name is possible, but buggy. Either it shouldn't be allowed (my vote), or we should fix the bugs. 

1. Deleting a data node identifier DOES NOT trigger "Save and Close" state. If an identifier is manually deleted from a data node, leaving all other fields of the xref intact, the "Save and Close" button is not triggered. Closing QuickEdit via "Close" button results in a buggy data node:
1.1 After reopening QuickEdit and selecting the node again, both identifier and display name are now blank.
1.2 In viewer mode, if clicking on the node, there is no update to the annotation panel from the previously selected node (as documented in #348), so the node behaves like an unannotated node. In addition, after selecting the buggy node, the annotation panel "gets stuck" on the node clicked immediately before the buggy node, meaning even if a normal node is selected there is no update in the annotation panel. If the annotation panel is manually closed, it doesn't come back when selecting another normal node.
1.3 Changes do not persist after refreshing the page, so nothing is saved.

2. Deleting the display name of a data node DOES trigger "Save and Close" as expected, but the resulting node is buggy:
2.1 The node appears WITHOUT display name in the viewer, but the annotation panel and QuickEdit still display the original display name. 
2.2 If the page is refreshed, the display name disappears as expected from the previous "Save and Close". But it doesn't happen until the page is refreshed.

As for editing the other two fields, changing data node type alone works as expected. However, changing datasource also doesn't trigger "Save and Close", and closing QuickEdit appears to have changed the node, but it is not saved after refresh. So similar to 2 above.

**Comment by ariutta** [comment]
+1 to "it shouldn't be allowed"

OK, @AlexanderPico?

**Comment by AlexanderPico** [comment]
Users should be able to delete identifiers and set datasource to none, e.g., when the entry is wrong and they don't know the correct information.   

I can't think of a good reason why label should be deleted.

But, how are you going to not allow users to delete these?

**Comment by ariutta** [comment]
There are validation libraries, e.g., http://parsleyjs.org/doc/examples/simple.html

**Comment by AlexanderPico** [comment]
I'd rather allow blank than add another library :)

**Comment by khanspers** [comment]
Updated bulleted lists in original description since they were not correct initially. Just to group the issues and sub-issues.

**Comment by khanspers** [comment]
Is it possible to just not allow a label with length zero, without the use of a library? The user should be able to manually edit this field, just not set it blank, right?

**Comment by ariutta** [comment]
Modern browsers have built-in form validation features: http://caniuse.com/#feat=form-validation

This does not include IE9.

**Comment by AlexanderPico** [comment]
I wouldn't do anything on this one. The current behavior is fine (re: 2, 2.1 and 2.2 above) for something that will rarely if ever happen.

The issue of triggering Save&Close when editing identifier (and/or datasource) is already fixed in #344

**Comment by AlexanderPico** [comment]
Refocused to #344 and #355
