### ISSUE TITLE
Safari: QuickEdit Close button missing

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#358]
In Safari (v 8.0.6), the Close button doesn't show up in QuickEdit. Maybe a css issue maybe? Attached is what inspect element shows, with the div titled Close highlighted. Looks like its hidden somehow. 

More evidence of this is that after making a change, like changing the identifier, the set of 4 entry fields get pushed down, presumably due to the larger Save and Close button, which is also not visible. See attached.
![screen shot 2015-07-29 at 11 35 31 am](https://cloud.githubusercontent.com/assets/1442197/8966448/4a209f20-35e6-11e5-9c9c-1ef4f57c68ea.png)
![screen shot 2015-07-29 at 11 04 49 am](https://cloud.githubusercontent.com/assets/1442197/8966458/533c177e-35e6-11e5-88b2-0c054eb434b0.png)

**Comment by ariutta** [comment]
I think you're right -- it must be a CSS issue.

**Comment by ariutta** [comment]
@AlexanderPico, I remember you working on this one in the past. Will you be able to take a look at it?

**Comment by ariutta** [comment]
Alex, we can break this into two parts:

1) Is this a showstopper for MVP release?
2) If yes, will you be able to get to it?

Thanks.

**Comment by AlexanderPico** [comment]
I can't get to it. It's a minor tweak to the css. Other things are broken in safari (I think), so I guess it's not a show stopper...

**Comment by ariutta** [comment]
In that case, all issues for the "editor-v1" milestone are now closed.

**Comment by AlexanderPico** [comment]
updated https://github.com/wikipathways/kaavio/blob/master/lib/stripped-bootstrap.css to resolve clash between navbar-right and navbar-form. Needs to be tested in all browsers.

**Comment by ariutta** [comment]
IE10/Win7:

![ie-bug](https://cloud.githubusercontent.com/assets/1296771/9044325/c107b9e6-39d0-11e5-820b-beace85cce7f.png)

**Comment by ariutta** [comment]
AP comment: "That change needs to be tested in all browsers, then tweaked if not sufficient. Explanation: instead of shifting button to the right, I shifted the annotation fields down so that they won’t clash even if they extend to the right."

I'm afraid I don't know how to tweak this to work in IE and Safari. If I try to address it, these are the only ways I know of:
1) apply a border to only the top, left and right sides, not the bottom
2) use the flexbox model

**Comment by AlexanderPico** [comment]
Try (1) first. It's lower risk and should take minutes. Refactoring to a new layout model will take time and require more thorough testing.

**Comment by ariutta** [comment]
OK, it's kind of working now. It still looks a little off in FF, but it's at least semi-usable. Note that the styling depends in part on the WikiPathways MediaWiki CSS, meaning this likely could result in problems if someone tried using the pvjs library on their own page (using the JS, not the widget).

**Comment by khanspers** [comment]
This is still happening in Safari, that is the fields are aligned correctly but once a change is made the fields are all moved down and the Save/Close button is missing.

**Comment by ariutta** [comment]
Hmm... this one is tricky. What happened when I closed it was I noticed it looked wrong in IE on my local test server, but then it looked fine in IE on the rcbranch server. So I didn't actually do the border change, but if it isn't working in Safari, I guess we'll need to make that happen.
