### ISSUE TITLE
Safari: Viewer window shifts slightly when clicking on pathway objects

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#359]
Safari v8.0.6

This one is hard to explain, but when clicking on data nodes, the entire viewer window shifts (wiggles?) a tiny bit to the left and then back to its original position.

**Comment by khanspers** [comment]
This also happens when clicking the Bold and Italic buttons in Properties, in QuickEdit. Interestingly, clicking the broken color chooser only shifts the whole window to the left, it doesn't shift back to original position until one of the other buttons are clicked. Maybe this helps in deciphering the problem.

**Comment by ariutta** [comment]
This one is odd. I think it's not a showstopper, so can we mark it as "after-editor-v1-released"?

**Comment by khanspers** [comment]
Don't see this behavior anymore. Closing.
