### ISSUE TITLE
Firefox: SVG of old gpml displayed while pathway is loading

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#361]
On rcbranch, in Firefox 34.0.5.

When refreshing the pathway page, the svg of the old gpml is displayed in the viewer for about 1-2 seconds while loading, which doesn't look great. Maybe this is just due to slower loading on rcbranch? On the live site, in FF, I don't see the old gpml displayed while loading, and the loading is much faster.

**Comment by ariutta** [comment]
This is due to the svg of the old gpml being displayed as a fallback, even while waiting for the pvjs svg to be rendered. We need to re-enable pvjs to accept multiple input types (e.g., gpml, png, etc.) to avoid this problem.

**Comment by khanspers** [comment]
I don't see this anymore, closing.
