### ISSUE TITLE
Default colors in color-picker

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#362]
@khanspers, would you be able to double-check the default colors in the color picker? You can edit the list here:
https://github.com/wikipathways/kaavio-editor/blob/master/lib/sub-components/color-picker-control.js#L48

(Here is the link that is fixed in time:
https://github.com/wikipathways/kaavio-editor/blob/2e3875eb3af8d56af0011c722210f7418531a7c6/lib/sub-components/color-picker-control.js#L48)

**Comment by ariutta** [comment]
I don't think I put quite the right green value in that list.

**Comment by khanspers** [comment]
https://github.com/wikipathways/kaavio-editor/commit/1d05c61772ae63b3147d450689ec2da6200c0695
