### ISSUE TITLE
Opening editor quickly/large pathways

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#367]
For large pathways, such as this one:
http://rcbranch.wikipathways.org/index.php/Pathway:WP385

a user might open the editor before the pathway's Xrefs are fully parsed. If the user then clicks a DataNode that has a valid Xref, the editor will throw an error and not show the Xref data in the annotation tab of the editor. So far, this has only happened for me in IE testing.

@AlexanderPico, is this a showstopper for editor-v1-release?

**Comment by ariutta** [comment]
Got it happen in Chrome too by clicking fast. It works fine if the user waits a bit until the Xrefs are fully parsed - we just aren't handling the case where the user opens the editor and clicks a DataNode before the parsing is done.

**Comment by AlexanderPico** [comment]
Not a showstopper. Patience is virtue :)

**Comment by khanspers** [comment]
I had trouble even reproducing this, you have to be extremely fast to encounter this issue. Changing label from bug to enhancement.
