### ISSUE TITLE
Selecting already assigned identifier from search results (so changing neither of id, type, label, database) prompts Save and Close

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#368]
Browsers observed: Safari, Chrome, Firefox
1. Select any data node
2. Search for the label
3. Select from the results the exact same identifier that is already assigned.

Expected: Close button should be visible
Observed: Close button changes to Save and Close even though nothing has actually changed in the xref

If I manually try to delete parts of either identifier or label, and then retype it exactly as it was, I get the Close button. But not if selecting the exact same id from the search results. Maybe there's a carriage return or some other hidden character in either the label or identifier being returned from bridgedb that causes pvjs to see it as different than what was there before.

Not huge problem, but should be fixed eventually since its confusing and adds to the history table unnecessarily.

**Comment by AlexanderPico** [comment]
In other cases like this, even though the Close&Save is triggered, it actually doesn't save and bloat the history table. IOW, a second diff is performed before deciding to save. So, while this is still not great UX, at least the history table (and web service) is not overused.

**Comment by khanspers** [comment]
Right, my initial description is incorrect. If I make a manual edit to the identifier, and then undo the edit manually (basically deleting and the retyping the last number), then Save and Close is also triggered. However, in that case there is no entry in the history table, but there is in the case described above, where I select the identical xref from search results. Just to clarify.

**Comment by ariutta** [comment]
Agreed. I think BridgeDb returns additional data about the entity reference. We should probably base the diff on the entities, not the entity references  (e.g., if a DataNode is listed as a specific instance of TP53, we wouldn't indicate a change if BridgeDb gave us more information about TP53 in general).

But if the display name of an entity changes, we would still indicate a change.

----- Original Message -----
