### ISSUE TITLE
Chrome: Color chooser height is not right

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#369]
The color choose drop-down does not fill the button, the height is set to 18px for the "color-palette", but the "input-group" div has a height of 30px. See attached.
![screen shot 2015-08-11 at 1 43 25 pm](https://cloud.githubusercontent.com/assets/1442197/9210785/1a526a60-4033-11e5-879a-0fff0b3d2c6b.png)

**Comment by AlexanderPico** [comment]
We couldn't make it taller... I just checked this in:
https://github.com/wikipathways/kaavio-editor/commit/87520dd3d27e6169dc68dd3c6a2cfa5afe16c44f
which at least centers it vertically, making it look a bit better, but not perfect.

**Comment by ariutta** [comment]
Do you need a new build before release?

----- Original Message -----

**Comment by AlexanderPico** [comment]
nah, not for this. I'll just change it in the minified :)

**Comment by khanspers** [comment]
The height of the color choose is still the same but it is now centered. The same in FF. Low priority.
