### ISSUE TITLE
Compartments and interactions still selectable

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#371]
Observed in all browsers:

Compartment shapes and interactions are still selectable, however they of course can't be edited in QuickEdit. This is potentially confusing. Are they supposed to be selectable?

**Comment by ariutta** [comment]
Currently, we just have one selection highlighter for all cases - annotation details panel in the viewer, annotation tab in the editor, properties tab in the editor... 

The editor is disabled based on what you've selected. It might not be the easiest, but we could possibly change the selection highlighter based on different criteria, such as when an interaction is selected and the editor properties tab is open. But I think we might be better off changing the editor tabs based on the current selection. For example, if the current selection cannot have annotations, we would just not show the annotation tab.

----- Original Message -----

**Comment by AlexanderPico** [comment]
How easy is this one to fix? Would be nice UX enhancement as selection indicates some sort of action/purpose, yet nothing happens at all...

**Comment by ariutta** [comment]
I'm not sure about the relationship we want between selection and action. The selection happens before the action, but should the action be responsible for indicating selection?

**Comment by AlexanderPico** [comment]
Sorry. Ignore that comment. I simply meant that we should disable selection of compartments.

**Comment by ariutta** [comment]
Simplest option is just changing the CSS for pvjs to make them non-selectable. Sound good?

**Comment by AlexanderPico** [comment]
yup
