### ISSUE TITLE
Some identifiers don't show up in quick edit

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#375]
Activate Quick Edit on this pathway (http://www.wikipathways.org/index.php/Pathway:WP2603) and then click on any of the nodes. You'll see no information for identifiers. But if you look at the bottom of the page (or the gpml) you'll see that there is information.

I suspect our editor is too stringent in only displaying/allowing IDs and datasources that are in BridgeDb.  For some species (like plants), authors have to use datasources that are not yet supported by BridgeDb. I wonder if we can add  datasources from a given GPML to the list of acceptable datasources in Quick Edit? That way users could view and edit these.

**Comment by ariutta** [comment]
If the node has a db, it should currently show up in the dropdown,
regardless of whether it's at BridgeDb. If not, that's a bug. But if the db
is not in BridgeDb, it will only show up if it's specified for that
specific node. Should we whitelist all dbs present for any node in a given
pathway? Should we also allow for user-specified dbs, maybe by giving an
option for "Other", so the user can enter it in an input box?

Identifiers should always show up in the input box if they're specified in
the GPML, although I'm not sure about the case where only one of db and
identifier is specified. If only one is specified, the editor might
possibly display/save neither at present (not sure).

**Comment by AlexanderPico** [comment]
Then it's a bug... Here's a snippet of GPML for one of the datanodes:
 <DataNode TextLabel="Beta vulgaris FLOWERING LOCUS T 2&#10;(BvFT2)" GraphId="e84e9" Type="GeneProduct">
    <BiopaxRef>f9d</BiopaxRef>
    <Graphics CenterX="656.7163009404388" CenterY="394.3336990595611" Width="187.0" Height="41.0" ZOrder="32768" FontSize="10" Valign="Middle"/>
    <Xref Database="EMBL" ID="HM448911"/>
  </DataNode>

You can see that an Xref Database and ID are provided, but neither show up in Quick Edit.

If these were to show up and allow someone to edit, say just the ID, and save it (even if the Database is not in BridgeDb), then that is a perfect solution. It sounds like that is how it is supposed to work.

No need to whitelist these Databases beyond the scope of a given pathway, but indeed, if it's used for one datanode, then it would be nice to see it as an option for other datanodes on the same pathway.  Adding "other" might not be a bad idea as well, if easy.  But both of these are "enhancements" that we can post in a new ticket if the "bug" aspect can be dealt with first.
