### ISSUE TITLE
QuickEdit saving is broken

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#376]
Looks like QuickEdit changes are not being saved. Tried on a couple of pathways, one of which was Sandbox (tried adding annotation to the Substrate node to the left). Searching seems broken (see other issue) so I manually entered an ID, chose a data source and "Save & Close" was triggered as expected. Closed QuickEdit, but after refresh the change is not saved.

**Comment by ariutta** [comment]
WikiPathways has an issue with the API at the moment. I suspect that's where this is coming from.

**Comment by ariutta** [comment]
Closing for now since Nuno is supposed to be fixing API. Will re-open if the issue still exists after Nuno is done.
