### ISSUE TITLE
Including scripts from wikipathways.github.io/pvjs leads to 404

### ISSUE THREAD

**Issue by noplacetoh1de** [wikipathways/pvjs#381]
As described in the Readme, I've tried to include the pvjs-scripts, but both lead to an 404 error.

<script src="//wikipathways.github.io/pvjs/lib/pvjs/pvjs-polyfills-2.3.5.bundle.min.js"></script>

<script src="//wikipathways.github.io/pvjs/lib/pvjs/pvjs-2.4.84.bundle.min.js"></script>

**Comment by ariutta** [comment]
Thanks for pointing this out. I'm working on making sure my installations instructions work now :)

**Comment by ariutta** [comment]
Until I get a working version built again, I know it's working on the wikipathways.org site, and I just extracted out the relevant code:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" type="text/javascript"></script>
<script src="//mithril.js.org/archive/v0.2.2-rc.1/mithril.min.js" type="text/javascript"></script>
<script src="/wpi/lib/pvjs/release/polyfills.bundle.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.2/CustomElements.min.js" charset="utf8"></script>
<script src="/wpi/lib/pvjs/release/pvjs.core.min.js" type="text/javascript"></script>
﻿﻿<script src="/wpi/lib/pvjs/release/pvjs.custom-element.min.js" type="text/javascript"></script>

<wikipathways-pvjs id="pvjs-container" class="wikipathways-pvjs kaavio-container" resource="http://identifiers.org/wikipathways/WP2226" version="79239&quot;" src="http://wikipathways.org/img_auth.php/2/21/WP2226_79239.gpml" display-errors="true" display-warnings="true" manual-render="true" editor="disabled" fit-to-container="true"><div style="width: inherit; height: inherit;"></wikipathways-pvjs>
```

**Comment by iseekwonderful** [comment]
hello, i set up a test case base on the code above, but only works on chrome, failed on safari and firefox without any error, the simple html file:
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>hello world</title>
    <script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" type="text/javascript"></script>
    <script src="//mithril.js.org/archive/v0.2.2-rc.1/mithril.min.js" type="text/javascript"></script>
    <script src="//wikipathways.org/wpi/lib/pvjs/release/polyfills.bundle.min.js" type="text/javascript"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/0.5.2/CustomElements.min.js" charset="utf8" type="text/javascript"></script>
    
    <script src="//wikipathways.org/wpi/lib/pvjs/release/pvjs.core.min.js" type="text/javascript"></script>
    <script src="//wikipathways.org/wpi/lib/pvjs/release/pvjs.custom-element.min.js" type="text/javascript"></script>

</head>
<body>
    <wikipathways-pvjs style="width: 800px; height: 600px;"
    alt="WP525 Biological Pathway"
    src="./WP2226_79239.gpml"
    display-errors="true"
    display-warnings="true"
    fit-to-container="true">
    </wikipathways-pvjs>
</body>
</html>`

could you please help me out or give some hint?
