### ISSUE TITLE
Bug with a pathway for new pvjs version

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#403]
http://dev.wikipathways.org/wpi/PathwayWidget.php?id=WP2204

**Comment by ariutta** [comment]
It might be simply that WP2204 doesn't exist on the dev server.

**Comment by AlexanderPico** [comment]
The GPML is there: http://dev.wikipathways.org/index.php/Pathway:WP2204
You can see the GPML if you click 'edit' or 'view source'. But it's not being rendered on the pathway page either.

**Comment by jacobwindsor** [comment]
The pathway page doesn't have the new Pvjs version on the dev server yet
