### ISSUE TITLE
node labels go blank with zoom in/out

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#406]
On dev, if you zoom in or out more than a few steps (using controls or scroll wheel), the node labels go blank and do not return

**Comment by jacobwindsor** [comment]
That's strange, I've not seen that. Can you specify what browser and
version you're using? Do the labels come back if you continue zooming in or
out or zoom the other way?

**Comment by AlexanderPico** [comment]
Note: "on dev"  We are testing the latest version at dev.wikipathways.org. Can you reproduce there?

No labels do not return.

This is see on FF. Not seen on Chrome.

**Comment by AlexanderPico** [comment]
![screen shot 2017-08-04 at 3 00 33 pm](https://user-images.githubusercontent.com/1418193/28989007-94f0541a-7927-11e7-9514-5a8ca6a4f45a.png)

**Comment by AlexanderPico** [comment]
Need to test when scroll-zoom is back.  We think it's already fixed...

**Comment by AlexanderPico** [comment]
fixed
