### ISSUE TITLE
Diagrams not loading

### ISSUE THREAD

**Issue by jacobwindsor** [wikipathways/pvjs#409]
One known bug for the React version of Pvjs is that some diagrams don't load.

@khanspers has found an interesting pathway [here](https://github.com/jacobwindsor/pathway-presenter/issues/5) that does load, just very slowly. This may be interesting for debugging

**Comment by AlexanderPico** [comment]
These all load now for pvjs and in reasonable time, as tested on dev.wikipathways.org
