### ISSUE TITLE
Hide pathway element params from svg

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#411]
These params are either outdated or redundant. Can we simply hide this element from the Pathway Page and Widget renderings?

I'm referring to the Name, Last Modified and Organism in the screenshot. If there are references associated to this element, it's okay to hide them as well. They are redundant with the bibliography on the pathway page, and don't provide any useful info on their own.
![screen shot 2017-10-10 at 11 02 28 am](https://user-images.githubusercontent.com/1418193/31402501-007bfb0a-adab-11e7-8545-19118e2846fe.png)

**Comment by ariutta** [comment]
We can definitely do that.

One question: the [widget](http://wikipathways.org/index.php/PathwayWidget) doesn't include the title and authors. Should we include some metadata for the widget view, maybe like this:
![widget-with-title-bar](https://user-images.githubusercontent.com/1296771/31901841-906885a4-b7d7-11e7-9cae-3b105dc3b416.png)

**Comment by ariutta** [comment]
Or we could update the metadata and keep the current infobox just for the widget.

**Comment by AlexanderPico** [comment]
Let's ditch the current infobox.  It's a good idea to discuss with Widget users about possible new features for displaying title and authors. But for now, let's just remove the bad info.

**Comment by khanspers** [comment]
Possible regression: Viewer on dev site shows additional fields from Pathway Information that is not shown on main site. See attached, showing License field.

I know the plan is to show nothing, but not sure of the timing (this is labeled 1.1, is that the next release?). If we are not completely removing the info box for the next release, then at least we shouldn't show more information than before. 

<img width="581" alt="screen shot 2017-11-29 at 1 02 30 pm" src="https://user-images.githubusercontent.com/1442197/33398951-9856e7a6-d505-11e7-8c0e-7ad2a9347ff6.png">
<img width="514" alt="screen shot 2017-11-29 at 1 02 18 pm" src="https://user-images.githubusercontent.com/1442197/33398952-987c3de4-d505-11e7-86ef-3f4ba75856e0.png">
