### ISSUE TITLE
Updating URLs

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#412]
Not sure which of these are relevant anymore, but they are changing:

* http://webservice.bridgedb.org -> **https**://webservice.bridgedb.org
  * e.g., https://github.com/wikipathways/pvjs/blob/master/lib/bridgedb/main.js#L52

* all references to pointer.ucsf.edu will be deadlinks soon
  * e.g., https://github.com/wikipathways/pvjs/search?utf8=%E2%9C%93&q=pointer&type=

**Comment by AlexanderPico** [comment]
Can you do a recursive string search for "http://webservice.bridgedb.org" and for "pointer"?

**Comment by ariutta** [comment]
We have `pointer-events` (unrelated) in the CSS, but these queries return nothing for pvjs:
```
grep -rI "pointer\." lib/
grep -rI "pointer\." dist/
grep -rI "webservice\." lib/
grep -rI "webservice\." dist/
```

bridgedbjs was using `http://webservice...`, but that's [now updated](https://github.com/bridgedb/bridgedbjs/commit/19ecbe9cc7ee34179f8ec6af5bfdd224a5ffa7b7).
