### ISSUE TITLE
Stretched Rounded Rectangles are Not Quite Right

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/pvjs#415]
Compare cell wall in: 

dev:
http://dev.wikipathways.org/index.php/Pathway:WP2839

current:
http://wikipathways.org/index.php/Pathway:WP2839

**Comment by ariutta** [comment]
How important is this? Must be fixed before next release?

**Comment by AlexanderPico** [comment]
It's worth 4 hours...  it is harder than that?

**Comment by ariutta** [comment]
It could be -- not sure. We're using SVG filters on SVG symbols to turn a single line into a double line, so we'd either need to tweak the filters or else not use SVG symbols. Here's relevant code:

* https://github.com/wikipathways/gpml2pvjson-js/blob/f85333af781c4b0780a2d86d1c19e4739223015c/src/2013a/ValueMappings.json#L37
* https://github.com/wikipathways/gpml2pvjson-js/blob/f85333af781c4b0780a2d86d1c19e4739223015c/src/Processor.ts#L348
* https://github.com/wikipathways/kaavio/blob/883dcb7d178ff7ebdfc07328e49dde13e8e5d955/src/components/Filter/FilterDefs.tsx
* https://github.com/wikipathways/kaavio/blob/883dcb7d178ff7ebdfc07328e49dde13e8e5d955/src/drawers/filters/index.tsx#L11

**Comment by ariutta** [comment]
We can either use pre-drawn SVGs like [these](https://github.com/wikipathways/kaavio/tree/universal/src/drawers/icons) as [SVG symbols](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol) or we can draw a new icon every time it's needed: https://github.com/ariutta/cross-platform-shapes

**Comment by AlexanderPico** [comment]
What did we do before? I don't have a preference on the technical details. Which ever works.

**Comment by ariutta** [comment]
This README has some good notes: https://github.com/wikipathways/kaavio/tree/c1b5f0d9b39ea62677312e02ebcaeb16f72fd95a/lib/shape-library

**Comment by ariutta** [comment]
We used the [cross-platform-shapes](https://github.com/ariutta/cross-platform-shapes) library.

**Comment by AlexanderPico** [comment]
It worked great, right?  Should we move that into wp repo and use it again?

**Comment by ariutta** [comment]
Moved discussion to slack.

**Comment by ariutta** [comment]
The double lines appear to be fine (let me know if you see any examples that are not OK!).

The rounding of the rectangle is not OK.

Plan: look at whether I can make the rounding work with existing code. Ideas: use a better SVG filter for rounding or use different symbols for different aspect ratios. If that doesn't work, I'll use cross-platform-shapes.

**Comment by ariutta** [comment]
Here's a simplified example of the relevant SVG: http://plnkr.co/edit/o2ldeQJzfSRwwLFxv44J?p=preview
