### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#416]
Display an error if the pathway cannot be rendered.

**Comment by AlexanderPico** [comment]
Also see #372. We need an alt way to display errors.

**Comment by AlexanderPico** [comment]
E.g., pathways with nested groups. If nothing is going to be rendered, we should post a message to users.

**Comment by AlexanderPico** [comment]
Are all warnings suppressed in new code? Or was this particular case just fixed?
https://www.wikipathways.org/index.php/Pathway:WP1946
http://dev.wikipathways.org/index.php/Pathway:WP1946

**Comment by AlexanderPico** [comment]
Backup to show png doesn't appear to be working:
http://dev.wikipathways.org/index.php/Pathway:WP803

**Comment by AlexanderPico** [comment]
fixed
