### ISSUE TITLE
Text label area of data nodes not responsive to clicking, so no annotation panel loading

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#418]
One the area outside the text label on nodes appears to be responsive to clicking (i.e. cursor is an arrow). So trying to click in the middle of data nodes doesn't bring up the annotation panel (cursor is changed to the "I-beam" pointer, which is typical when editing text). 

This could be problematic for nodes with large labels that fill up most of the node, and could be confusing in general because the behavior is not consistent.

**Comment by ariutta** [comment]
Good catch!

**Comment by AlexanderPico** [comment]
fixed
