### ISSUE TITLE
Zoom and reset repositions the pathway

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#419]
Procedure:
Open http://dev.wikipathways.org/index.php/Pathway:WP528. Click on "Phosphorylcholine" node to bring up annotation panel (or any other node along the perimeter). Double-click again on the same node to zoom. Click reset. The pathway is now repositioned, centered on the clicked node. To reset back to the starting point, clicking reset again works. Is this the expected behavior?

**Comment by ariutta** [comment]
No, this is not the expected behavior. Is it a showstopper for the next release of pvjs, or can this be fixed after?

**Comment by khanspers** [comment]
Probably not a showstopper.

**Comment by ariutta** [comment]
@AlexanderPico feel free to change milestone, but I'm marking this as not a showstopper.

**Comment by khanspers** [comment]
Update: Actually this happens after any zoom, to test this it is not necessary to first click on a node. Simply double-click anywhere to zoom, click reset and the pathway will be repositioned.

**Comment by DeniseSl22** [comment]
Normally, I could zoom in on a pathway with my mouse by using the scroll wheel; now I have to click the + or - to zoom in or out. Is this what you want for visualisation?

**Comment by khanspers** [comment]
Ah, I see that too now. Scroll to zoom (mouse or trackpad) doesn't work anymore.

**Comment by DeniseSl22** [comment]
Yes that is what I meant (but you explain it better Kristina ;)...)
