### ISSUE TITLE
Annotation panel appears for group node

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#422]
Looks like an annotation panel is pulled up when clicking on a group node, meaning neither of the actual nodes in the group, but rather the group itself. For example, try clicking on the shaded area around PDHA1 and PDHA2 in this pathway: http://dev.wikipathways.org/index.php/Pathway:WP528

The annotation panel pops up with a message saying the node has no annotation. 
![screen shot 2017-11-29 at 10 47 48 am](https://user-images.githubusercontent.com/1442197/33393180-2992d79c-d4f3-11e7-8803-f80eea4bb49c.png)

**Comment by DeniseSl22** [comment]
For this PW, there is no annotation panel at all:
http://dev.wikipathways.org/index.php/Pathway:WP1601

**Comment by khanspers** [comment]
@DeniseSl22: There is a bug where only the non-label area of nodes are clickable. I think that's what you are seeing. https://github.com/wikipathways/pvjs/issues/418

**Comment by DeniseSl22** [comment]
Ah yes I see it now. And the annotation panel appears on the left top only.... is that how the visualisation should be? The original visualisation of the panel, is next to the node you clicked on, right?

**Comment by khanspers** [comment]
Right, top left positioning is by design, because it doesn't obscure nodes as much.

**Comment by DeniseSl22** [comment]
Okay, good to know!

**Comment by AlexanderPico** [comment]
fixed
