### ISSUE TITLE
Search function doesn't work (yet) on http://dev.wikipathways.org/index.php/WikiPathways

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/pvjs#423]
Hi all,

I cannot use the search function now :(

![image](https://user-images.githubusercontent.com/26277832/33394507-dce466f4-d542-11e7-8b58-eae77056bf74.png)

**Comment by AlexanderPico** [comment]
Right. We only have indexer support for the main site and for rcbranch. The release candidate code can be fully tested on rcbranch, prior to release on the main site. But "dev" has a few missing features like this one.
