### ISSUE TITLE
Data node states coloring and label attributes are wrong

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#424]
Data node states have a teal fill color, and the label is white and bold (it looks like at least). States should  not have any fill or text label alterations, other than what the author has specified in gpml. 

See
http://dev.wikipathways.org/index.php/Pathway:WP673
http://dev.wikipathways.org/index.php/Pathway:WP2868
http://dev.wikipathways.org/index.php/Pathway:WP3972

**Comment by AlexanderPico** [comment]
confirming this is still an issue
![screen shot 2017-12-06 at 5 13 35 pm](https://user-images.githubusercontent.com/1418193/33693656-d937c2ce-daa8-11e7-8351-d5e73c2d0964.png)

**Comment by AlexanderPico** [comment]
fixed
