### ISSUE TITLE
Group styles are not always displayed 

### ISSUE THREAD

**Issue by khanspers** [wikipathways/pvjs#425]
Groups styles (complex, pathway, none) are not always displayed the same as what shows on the main site. Looks like it is related to pathways specifically using 2013a schema. Is this not supported in the new viewer?

Problem pathways:
http://dev.wikipathways.org/index.php/Pathway:WP4 
http://dev.wikipathways.org/index.php/Pathway:WP2636
http://dev.wikipathways.org/index.php/Pathway:WP1403

Pathways that are ok:
http://dev.wikipathways.org/index.php/Pathway:WP78
http://dev.wikipathways.org/index.php/Pathway:WP528

<img width="717" alt="screen shot 2017-11-29 at 1 49 46 pm" src="https://user-images.githubusercontent.com/1442197/33400850-3648ace6-d50c-11e7-9c69-512c0380bc48.png">
<img width="788" alt="screen shot 2017-11-29 at 1 49 41 pm" src="https://user-images.githubusercontent.com/1442197/33400852-36630fc8-d50c-11e7-8648-d3b3a558d244.png">

**Comment by AlexanderPico** [comment]
Confirming this is still an issue. Specifically, notice how the complex borders are missing in this pathway and the complex name labels are displayed in the center. 

http://dev.wikipathways.org/index.php/Pathway:WP2636
https://www.wikipathways.org/index.php/Pathway:WP2636

![screen shot 2017-12-06 at 5 16 49 pm](https://user-images.githubusercontent.com/1418193/33693767-761483fc-daa9-11e7-8c2a-f50434b6a307.png)

**Comment by ariutta** [comment]
[This commit](https://github.com/wikipathways/gpml2pvjson-js/commit/92f0d6a83455093dda96a031e43724c7254f64fc) was needed for Complex shape to show.

**Comment by khanspers** [comment]
WP4 on dev site still shows the group styles incorrectly. 

- The top left group is style "none" and should be a dashed outline beige rectangle
- The mitochondria is in a group with style "pathway" so should be in a green rectangle with dashed outline. 
Looks like style Complex is fixed though.

http://dev.wikipathways.org/index.php/Pathway:WP4
https://www.wikipathways.org/index.php/Pathway:WP4

**Comment by AlexanderPico** [comment]
I agree on the group with style "none", but I don't understand of the use of the pathway group. Do we have any real cases of how this is used and should be rendered?

**Comment by khanspers** [comment]
Right, the pathway style is almost never used. I found one occurence (did grep on Oct download for all species), and actually in this case it renders just fine:
http://dev.wikipathways.org/index.php/Pathway:WP3670

**Comment by AlexanderPico** [comment]
Ah, then it not a bug :)  I tried to update WP4 on dev and broke it somehow...  Sorry!

Do we have any real examples of the group "none"?

**Comment by khanspers** [comment]
Don't know off hand of real examples of group style none, and can't d a grep for a it because they way its defined is simply without the "style=" parameter, so nothing to search for......

**Comment by AlexanderPico** [comment]
Here's one:
http://dev.wikipathways.org/index.php/Pathway:WP1539

They are rendered properly...

I think the sandbox pathway is an exception for some reason...
