### ISSUE TITLE
Can't import pvjs 4.0.0-x

### ISSUE THREAD

**Issue by thomaskelder** [wikipathways/pvjs#433]
Trying to use the pvjs React component, but the module doesn't seem to import. When following the example, I get a "could not resolve dependencies" (on my local installation), or "could not find the module" (in sandbox below):

https://codesandbox.io/s/v3zq8yoyzl

This seem to happen for versions of the npm package "@wikipathways/pvjs" from 4.0.0-1 on. Version 3.7.4-beta does not give me this error.

**Comment by thomaskelder** [comment]
Could it be cause by missing index.js?

Looking at the git history, there is an index.ts.j in 22450ce9771ba8a8946ee5c5223a2a7390d3c8ac, but not anymore in f914fc38e1a3586a0a288edf44c64779a0a8ec71. The dates of these commits match the version change from 3.x to 4.x in the npm package.

**Comment by ariutta** [comment]
Hi @thomaskelder, thanks for reporting this. I'm looking into it now and will get back to you with an answer.

**Comment by ariutta** [comment]
Can you tell me which version of Node and NPM you are running?

**Comment by thomaskelder** [comment]
Hi @ariutta, 

Thanks for looking into it. Here's the output from npm version:
```
{ frontend: '0.1.0',
  npm: '5.6.0',
  ares: '1.13.0',
  cldr: '32.0.1',
  http_parser: '2.7.1',
  icu: '60.2',
  modules: '59',
  nghttp2: '1.29.0',
  node: '9.4.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.46-node.17',
  zlib: '1.2.11' }

```

**Comment by ariutta** [comment]
I think you're right about the source of the bug. I'll release another version soon with that corrected. In the meantime, you might try importing `dist/pvjs.js`.

**Comment by thomaskelder** [comment]
Thanks!
The workaround doesn't work for me, I'm getting:

```
Invariant Violation
Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```
(see https://codesandbox.io/s/jn2p23q23y)

Probably because the js file in the npm package is already minified. I'll await your update of the npm package.

**Comment by ariutta** [comment]
Hi @thomaskelder, I have another workaround. It's kind of ugly, because the API hasn't been decided yet, but you can copy [this example](https://github.com/wikipathways/pvjs/blob/702c79a4e9df7d027da3d95378e229e0ddbb9db6/test/index.html#L81). It's using `dist/pvjs.js`.

**Comment by egonw** [comment]
I'm guess this may have to do with `pvjs` not being available from unpkg.com anymore? E.g. this gist is not working either: https://gist.github.com/jacobwindsor/b45fdf2485a2e0c772fe2884c32ee9cc

**Comment by egonw** [comment]
@ariutta, might this because of outdated dependencies?
