### ISSUE TITLE
Symbols in Literature which are not recognised

### ISSUE THREAD

**Issue by DeniseSl22** [wikipathways/pvjs#434]
Hello! I don't know if this is a pvjs specific problem, but I encountered a PW where two of the literature references had weird symbols in them. This was because the 2 last names involved had hyphens on some vowels. Example PW: https://www.wikipathways.org/index.php/Pathway:WP229
It would be nice if the query done on pubmedIDs could handle these symbols as well (or perhaps it goes wrong later on, I don't know specifically).

**Comment by mkutmon** [comment]
not a pvjs issue but a java encoding issue that was partially resolved in PV release 3.1.0.  if you see these issues in pathways, feel free to fix them. New pathways should not have any of those symbols anymore.
