### ISSUE TITLE
Handle pathways with zero elements

### ISSUE THREAD

**Issue by ariutta** [wikipathways/pvjs#91]
Do we need to be able to handle pathways these kinds of pathways?
1) without edges
2) without nodes
3) without anything

**Comment by khanspers** [comment]
Somewhat related to #281

**Comment by khanspers** [comment]
Just like #190, don't see why this is tagged for diffviewer.

**Comment by ariutta** [comment]
The viewer should work for pathways with zero elements, but the diffviewer
may have thrown an error. I'll check once Nuno and I finish with the API
issue.

**Comment by khanspers** [comment]
Right, it works in FF, Safari and Chrome. Adding back the diffviewer tag.

**Comment by khanspers** [comment]
Also works in IE (Windows 7).
